# ./docker-compose.yml

version: '3'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      # MYSQL_DATABASE: "centrodiscusion"
      # MYSQL_USER: "centro"
      # MYSQL_PASSWORD: "discusion"
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/var/lib/mysql

  web:
    build:
      context: ./
      dockerfile: Dockerfile.php
    container_name: servidorweb
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true